// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskService.Data;

#nullable disable

namespace TaskService.Migrations
{
    [DbContext(typeof(MyAppDbContext))]
    [Migration("20250311180032_SeedTaskData")]
    partial class SeedTaskData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskService.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Completed = false,
                            Description = "Milk, eggs, bread",
                            Title = "Buy groceries"
                        },
                        new
                        {
                            Id = 2,
                            Completed = false,
                            Description = "Check in and say hello",
                            Title = "Call mom"
                        },
                        new
                        {
                            Id = 3,
                            Completed = false,
                            Description = "Complete the work report",
                            Title = "Finish report"
                        },
                        new
                        {
                            Id = 4,
                            Completed = false,
                            Description = "Organize and tidy up",
                            Title = "Clean room"
                        },
                        new
                        {
                            Id = 5,
                            Completed = false,
                            Description = "Electricity and internet",
                            Title = "Pay bills"
                        },
                        new
                        {
                            Id = 6,
                            Completed = false,
                            Description = "Read 10 pages of a novel",
                            Title = "Read book"
                        },
                        new
                        {
                            Id = 7,
                            Completed = false,
                            Description = "Go for a 30-minute walk",
                            Title = "Exercise"
                        },
                        new
                        {
                            Id = 8,
                            Completed = false,
                            Description = "Reply to pending emails",
                            Title = "Send email"
                        },
                        new
                        {
                            Id = 9,
                            Completed = false,
                            Description = "Make a healthy meal",
                            Title = "Cook dinner"
                        },
                        new
                        {
                            Id = 10,
                            Completed = false,
                            Description = "Relax and enjoy",
                            Title = "Watch a movie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
